theme: jekyll-theme-minimal
title: Elizabeth Ferrick Kiddie, Ph.D.
description: This website includes information about me and includes programming and data science resources for my undergraduate researchers.
